import { StyleSheet } from "@react-pdf/renderer";

export const registryPdfStyles = StyleSheet.create({
  page: {
    paddingTop: 28,
    paddingHorizontal: 28,
    paddingBottom: 24,
    fontFamily: "Helvetica",
    fontSize: 9,
    color: "#0f172a",
    lineHeight: 1.35,
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderBottomWidth: 2,
    borderBottomColor: "#14b8a6",
    paddingBottom: 12,
    marginBottom: 12,
  },
  brand: {
    flex: 1,
    paddingRight: 12,
  },
  brandName: {
    fontSize: 18,
    fontWeight: 700,
    color: "#0f172a",
    marginBottom: 2,
  },
  brandMeta: {
    fontSize: 8,
    color: "#475569",
    marginBottom: 1,
  },
  titleBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
    borderRadius: 8,
    backgroundColor: "#f1f5f9",
    marginBottom: 12,
  },
  title: {
    fontSize: 11,
    fontWeight: 700,
    color: "#0f172a",
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 7.5,
    color: "#64748b",
  },
  badgeWrap: {
    alignItems: "flex-end",
  },
  badgeSperm: {
    fontSize: 8,
    fontWeight: 700,
    color: "#0f766e",
    backgroundColor: "#ccfbf1",
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 999,
    marginBottom: 2,
  },
  badgeEgg: {
    fontSize: 8,
    fontWeight: 700,
    color: "#be185d",
    backgroundColor: "#fce7f3",
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 999,
    marginBottom: 2,
  },
  regId: {
    fontSize: 7.5,
    color: "#64748b",
    fontFamily: "Helvetica-Bold",
  },
  section: {
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 8.5,
    fontWeight: 700,
    color: "#0f172a",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    borderBottomWidth: 0.8,
    borderBottomColor: "#cbd5e1",
    paddingBottom: 4,
    marginBottom: 8,
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#e2e8f0",
    paddingVertical: 3,
  },
  label: {
    width: "36%",
    fontSize: 8,
    color: "#64748b",
    fontWeight: 700,
    paddingRight: 8,
  },
  value: {
    flex: 1,
    fontSize: 8,
    color: "#0f172a",
  },
  twoColGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -4,
  },
  halfCell: {
    width: "50%",
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  card: {
    borderWidth: 0.75,
    borderColor: "#e2e8f0",
    borderRadius: 8,
    padding: 8,
    backgroundColor: "#ffffff",
  },
  infoGrid: {
    flexDirection: "row",
    marginHorizontal: -4,
  },
  infoLeft: {
    width: "28%",
    paddingHorizontal: 4,
  },
  infoRight: {
    width: "72%",
    paddingHorizontal: 4,
  },
  photo: {
    width: 88,
    height: 112,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    objectFit: "cover",
  },
  photoFallback: {
    width: 88,
    height: 112,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#cbd5e1",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8fafc",
    color: "#94a3b8",
    fontSize: 7.5,
    textAlign: "center",
    paddingHorizontal: 8,
  },
  photoCaption: {
    marginTop: 4,
    fontSize: 6.5,
    color: "#94a3b8",
    textAlign: "center",
  },
  checklistGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -4,
  },
  checklistItem: {
    width: "25%",
    paddingHorizontal: 4,
    marginBottom: 6,
  },
  checklistBox: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 6,
    backgroundColor: "#f8fafc",
    paddingVertical: 5,
    paddingHorizontal: 6,
    borderWidth: 0.5,
    borderColor: "#e2e8f0",
  },
  checklistLabel: {
    fontSize: 7.5,
    color: "#475569",
    paddingRight: 6,
    flex: 1,
  },
  checklistPresent: {
    fontSize: 7,
    color: "#0f766e",
    fontWeight: 700,
  },
  checklistMissing: {
    fontSize: 7,
    color: "#dc2626",
    fontWeight: 700,
  },
  signatures: {
    flexDirection: "row",
    marginTop: 12,
  },
  signatureCell: {
    width: "33.33%",
    paddingHorizontal: 6,
    alignItems: "center",
  },
  signatureLine: {
    width: "100%",
    minHeight: 22,
    borderBottomWidth: 0.75,
    borderBottomColor: "#cbd5e1",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBottom: 2,
    fontSize: 9,
    fontStyle: "italic",
  },
  signatureLabel: {
    marginTop: 4,
    fontSize: 6.5,
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    textAlign: "center",
  },
  footer: {
    position: "absolute",
    bottom: 18,
    left: 28,
    right: 28,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 6.5,
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
});
